version: 2
project_name: nrdot-collector-releases
release:
  draft: true
  disable: true
builds:
  # Oracle-enabled build - CGO enabled for Linux AMD64 and ARM64 (Oracle Instant Client support)
  - id: nrdot-collector-host-oracle
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    dir: _build
    binary: nrdot-collector-host
    ldflags:
      - -s
      - -w
      - -linkmode=external
    flags:
      - -trimpath
      - -buildmode=pie
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-none-linux-gnu-gcc
          - CXX=aarch64-none-linux-gnu-g++
          - CGO_ENABLED=1
archives:
  - id: nrdot-collector-host-oracle
    builds:
      - nrdot-collector-host-oracle
    name_template: 'nrdot-collector-host-oracle_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - src: config.yaml
nfpms:
  # Oracle-enabled packages (Linux AMD64 and ARM64 with CGO and cross-compilation support)
  - file_name_template: 'nrdot-collector-host-oracle_{{ .Version }}_{{ .Os }}_{{- if not (eq (filter .ConventionalFileName "\\.rpm$") "") }}{{- replace .Arch "amd64" "x86_64" | replace "arm64" "aarch64" }}{{- else }}{{- .Arch }}{{- end }}'
    package_name: nrdot-collector-host-oracle
    contents:
      - src: nrdot-collector-host.service
        dst: /lib/systemd/system/nrdot-collector-host.service
      - src: nrdot-collector-host.conf
        dst: /etc/nrdot-collector-host/nrdot-collector-host.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/nrdot-collector-host/config.yaml
        type: config
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: nrdot-collector-host-oracle
    builds:
      - nrdot-collector-host-oracle
    formats:
      - deb
      - rpm
    maintainer: New Relic <otelcomm-team@newrelic.com>
    description: NRDOT Collector - nrdot-collector-host (with Oracle Instant Client support via CGO)
    license: Apache 2.0
snapshot:
  version_template: '{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}'
checksum:
  name_template: '{{ .ArtifactName }}.sum'
  algorithm: sha256
  split: true
changelog:
  disable: true