version: 2
project_name: nrdot-collector-releases
release:
  draft: true
  disable: true
builds:
  - id: nrdot-collector-host
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: _build
    binary: nrdot-collector-host
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
      - -buildmode=pie
    env:
      - CGO_ENABLED=0
archives:
  - id: nrdot-collector-host
    ids:
      - nrdot-collector-host
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - src: config.yaml
nfpms:
  - file_name_template: >-
      {{ .PackageName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    package_name: nrdot-collector-host
    contents:
      - src: nrdot-collector-host.service
        dst: /lib/systemd/system/nrdot-collector-host.service
      - src: nrdot-collector-host.conf
        dst: /etc/nrdot-collector-host/nrdot-collector-host.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/nrdot-collector-host/config.yaml
        type: config
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: nrdot-collector-host
    ids:
      - nrdot-collector-host
    formats:
      - deb
      - rpm
    maintainer: New Relic <otelcomm-team@newrelic.com>
    description: NRDOT Collector - nrdot-collector-host
    license: Apache 2.0
msi:
  - id: nrdot-collector-host-msi
    name: 'nrdot-collector-host_{{ .Version }}_windows_amd64'
    wxs: nrdot-collector-host.wxs
    ids:
      - nrdot-collector-host
    extra_files:
      - config.yaml
snapshot:
  version_template: '{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}'
checksum:
  name_template: '{{ .ArtifactName }}.sum'
  algorithm: sha256
  split: true
changelog:
  disable: true
