# Systemd environment file for the nrdot-collector-host service
# Command-line options for the nrdot-collector-host service.
# Note: All YAML config files from /etc/nrdot-collector-host/ are automatically loaded
# See https://opentelemetry.io/docs/collector/configuration/ to see all available options.
OTELCOL_OPTIONS=""
